---
version: 2

project_name: pgbackrest_exporter

builds:
  - env: 
      - CGO_ENABLED=0
    goos: 
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags: 
      - -trimpath
      - -mod=vendor
    ldflags: "-s -w -X main.version={{ .Version }}"
    main: .

archives:
  - id: pgbackrest_exporter
    files:
      - LICENSE
    format: tar.gz
    name_template: '{{ .Binary }}-{{ .Version }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    wrap_in_directory: true

nfpms:
  - id: pgbackrest_exporter
    package_name: pgbackrest_exporter
    builds:
      - pgbackrest_exporter
    homepage: https://github.com/woblerr/pgbackrest_exporter
    maintainer: Anton Kurochkin
    description: Prometheus exporter for pgBackRest
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    file_name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    contents:
      - src: pgbackrest_exporter.service.template
        dst: /etc/systemd/system/pgbackrest_exporter.service
        type: config

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: true

changelog:
  disable: true
