FROM goreleaser/goreleaser:v1.24.0 as builder
WORKDIR /build
COPY . /build
RUN goreleaser release --snapshot --skip-publish --clean

FROM alpine
COPY --from=builder /build/dist/ /dist/
RUN mkdir -p /artifacts && \
    cp /dist/*.tar.gz /artifacts/ && \
    cp /dist/*.rpm /artifacts/ && \
    cp /dist/*.deb /artifacts/ && \
    cp /dist/*.txt /artifacts/ && \
    ls -la /artifacts/*
CMD ["sleep", "150"]